import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Portfolio | Gilang Arya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased overflow-x-hidden`}>
        {children}
        <Script
          src="//cdn.jsdelivr.net/npm/eruda"
          strategy="beforeInteractive"
        />
        <Script strategy="beforeInteractive">{`eruda.init();`}</Script>
      </body>
    </html>
  );
}
